/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package in.co.rahogata.cryptokeep;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App(new DataCryptor(), null);
        fail("Not yet implemented");
    }
}
